---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Data Management:
    - Immich:
        icon: immich
        href: https://photos.home.alsharafi.dev
        siteMonitor: http://immich_server:2283
        description: Photos service
    - OpenCloud:
        icon: open-cloud-dark
        href: https://cloud.home.alsharafi.dev
        siteMonitor: http://opencloud:9200
        description: File storage & sharing
- Media Stack:
    - Jellyfin:
        icon: jellyfin
        href: https://jellyfin.home.alsharafi.dev
        siteMonitor: http://jellyfin:8096
        description: Media server
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
            enableBlocks: true # optional, defaults to false
            fields: ["movies", "series", "episodes"]
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            enableMediaControl: true # optional, defaults to true
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: true # optional, defaults to true
    - Jellyseerr:
        icon: jellyseerr
        href: https://jellyseerr.home.alsharafi.dev
        siteMonitor: http://jellyseerr:5055
        description: Requests management
        widget:
            type: jellyseerr
            url: http://jellyseerr:5055
            key: {{HOMEPAGE_VAR_JELLYSEER_KEY}}
    - Sonarr:
        icon: sonarr
        href: https://sonarr.home.alsharafi.dev
        siteMonitor: http://sonarr:8989
        description: TV shows management
        widget:
            type: sonarr
            url: http://sonarr:8989
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
    - Radarr:
        icon: radarr
        href: https://radarr.home.alsharafi.dev
        siteMonitor: http://radarr:7878
        description: Movies management
        widget:
            type: radarr
            url: http://radarr:7878
            key: {{HOMEPAGE_VAR_RADARR_KEY}}
    - Prowlarr:
        icon: prowlarr
        href: https://prowlarr.home.alsharafi.dev
        siteMonitor: http://prowlarr:9696
        description: Indexers management
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}
    - Bazarr:
        icon: bazarr
        href: https://bazarr.home.alsharafi.dev
        siteMonitor: http://bazarr:6767
        description: Subtitles
         management
        widget:
            type: bazarr
            url: http://bazarr:6767
            key: {{HOMEPAGE_VAR_BAZARR_KEY}}
    - qBittorrent:
        icon: qbittorrent
        href: https://qbittorrent.home.alsharafi.dev
        siteMonitor: http://qbittorrent:8080
        description: Download client
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080
            username: {{HOMEPAGE_VAR_QBITTORRENT_USER}}
            password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
            enableLeechProgress: true # optional, defaults to false
            enableLeechSize: true # optional, defaults to false
    # - Flaresolverr:
    #     icon: flaresolverr
    #     href: https://flaresolverr.home.alsharafi.dev
    #     siteMonitor: http://flaresolverr:8191
    #     description: CloudFlare protection bypapss
        

- Tools & Utilities:
    - IT Tools:
        icon: it-tools
        href: https://utils.home.alsharafi.dev
        siteMonitor: http://it-tools:80
        description: Tools for developers
    - Omni Tools:
        icon: omni-tools
        href: https://tools.home.alsharafi.dev
        siteMonitor: http://omni-tools:80
        description: Collection of various tools 
    - Vert.sh:
        icon: sh-vert
        href: https://convert.home.alsharafi.dev
        siteMonitor: http://vert:80
        description: File conversion tool
    - Stirling PDF:
        icon: stirling-pdf
        href: https://pdf.home.alsharafi.dev
        siteMonitor: http://stirling-pdf:8080
        description: PDF editor
    - Bento PDF:
        icon: bentopdf
        href: https://pdf-tools.home.alsharafi.dev
        siteMonitor: http://bentopdf:8080
        description: PDF manipulation tools

- GRP:
    - Networking:
        - AdGuard Home:
            icon: adguard-home
            href: https://dns.home.alsharafi.dev
            siteMonitor: http://adguard:80
            description: Network-wide blocker
            widget:
            type: adguard
            url: http://adguard:80
            username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
            password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}

    - Core Infrastructure:
        - Traefik:
            icon: traefik
            href: https://traefik.home.alsharafi.dev
            siteMonitor: http://traefik:8080
            description: Reverse proxy & load balancer
            widget:
            type: traefik
            url: http://traefik:8080
        - Zitadel:
            icon: zitadel
            href: https://auth.home.alsharafi.dev
            siteMonitor: http://zitadel_login:3000/ui/v2/login/loginname
            description: Authentication provider
        - Kopia:
            icon: kopia
            href: https://kopia.home.alsharafi.dev
            siteMonitor: http://kopia:51515
            description: Automated backup tool
            widget:
            type: kopia
            url: http://kopia:51515
        - Arcane:
            icon: arcane
            href: https://arcane.home.alsharafi.dev
            siteMonitor: http://arcane:3552
            description: Docker management dashboard
        - Beszel:
            icon: beszel
            href: https://beszel.home.alsharafi.dev
            siteMonitor: http://beszel:8090
            description: System monitoring