services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./images:/app/public/images
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.alsharafi.dev
      HOMEPAGE_VAR_ADGUARD_USERNAME: "${ADGUARD_USERNAME}"
      HOMEPAGE_VAR_ADGUARD_PASSWORD: "${ADGUARD_PASSWORD}"
      HOMEPAGE_VAR_JELLYFIN_KEY: "${JELLYFIN_KEY}"
      HOMEPAGE_VAR_JELLYSEER_KEY: "${JELLYSEER_KEY}"
      HOMEPAGE_VAR_SONARR_KEY: "${SONARR_KEY}"
      HOMEPAGE_VAR_RADARR_KEY: "${RADARR_KEY}"
      HOMEPAGE_VAR_PROWLARR_KEY: "${PROWLARR_KEY}"
      HOMEPAGE_VAR_BAZARR_KEY: "${BAZARR_KEY}"
      HOMEPAGE_VAR_QBITTORRENT_USER: "${QBITTORRENT_USER}"
      HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "${QBITTORRENT_PASSWORD}"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.alsharafi.dev`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.middlewares=auth@file"

networks:
  proxy:
    external: true