services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./images:/app/public/images
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.home.alsharafi.dev
      HOMEPAGE_VAR_ADGUARD_USERNAME: "${ADGUARD_USERNAME}"
      HOMEPAGE_VAR_ADGUARD_PASSWORD: "${ADGUARD_PASSWORD}"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.home.alsharafi.dev`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.middlewares=auth@file"

networks:
  proxy:
    external: true